apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels: 
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers: 
        - name: nginx
          image: nginx