apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selectors: 
    matchLabels:
      app: nginx
  template:
    metadata:
      lables: 
        app: nginx
    spec: 
      containers:
      - name: nginx:alpine
        image: nginx:alpine
